print("enter the first number")
firstNumber=int(input())
print("enter the second number")
SecondNumber=int(input())
print(str(firstNumber)+" + "+str(SecondNumber)+"= "+str(firstNumber+SecondNumber))
print(str(firstNumber)+"-" +str(SecondNumber)+"=  "+str(firstNumber-SecondNumber))
print(str(firstNumber)+" * "+str(SecondNumber)+"= "+str(firstNumber*SecondNumber))
print(str(firstNumber)+"/" +str(SecondNumber)+"=  "+str(firstNumber/SecondNumber))
print(str(firstNumber)+"%" +str(SecondNumber)+"=  "+str(firstNumber%SecondNumber))